base_config: ../base_config.yaml
dataset:
  language: en
  name: squad_v2
  unanswerable_ratio: 0.33
generation:
  do_sample: true
  no_repeat_ngram_size: 3
  num_beams: 1
  num_return_sequences: 50
  temperature: 1.0
  top_k: 50
  top_p: 0.95
language: en
lora:
  enabled: true
  lora_alpha: 64
  lora_dropout: 0.1
  r: 32
mode: answer_agnostic
model_name: facebook/bart-base
tokenizer_name: facebook/bart-base
training:
  num_epochs: 5
  output_dir: ./checkpoints/bart_base_en_agnostic
